#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ahinko.android.credimax.Resource", IsApplication=true)]

namespace ahinko.android.credimax
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::ahinko.android.credimax.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::ahinko.android.credimax.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::ahinko.android.credimax.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int bg = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int GradientEditTextStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_shopping = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int monoandroidsplash = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int radialBackground = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int roundButton = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int splash = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int TextViewRedStyle = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080012
			public const int MyButton = 2131230738;
			
			// aapt resource value: 0x7f080019
			public const int add = 2131230745;
			
			// aapt resource value: 0x7f080015
			public const int btnBorrar = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int btnBuscar = 2131230742;
			
			// aapt resource value: 0x7f080011
			public const int btnConfirm = 2131230737;
			
			// aapt resource value: 0x7f080010
			public const int btnNumPad_Cero = 2131230736;
			
			// aapt resource value: 0x7f08000e
			public const int btnNumPad_Eight = 2131230734;
			
			// aapt resource value: 0x7f08000b
			public const int btnNumPad_Five = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int btnNumPad_Four = 2131230730;
			
			// aapt resource value: 0x7f08000f
			public const int btnNumPad_Nine = 2131230735;
			
			// aapt resource value: 0x7f080007
			public const int btnNumPad_One = 2131230727;
			
			// aapt resource value: 0x7f08000d
			public const int btnNumPad_Seven = 2131230733;
			
			// aapt resource value: 0x7f08000c
			public const int btnNumPad_Six = 2131230732;
			
			// aapt resource value: 0x7f080009
			public const int btnNumPad_Three = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int btnNumPad_Two = 2131230728;
			
			// aapt resource value: 0x7f080000
			public const int btnShoppingCar = 2131230720;
			
			// aapt resource value: 0x7f08001c
			public const int call = 2131230748;
			
			// aapt resource value: 0x7f080017
			public const int contentFrame = 2131230743;
			
			// aapt resource value: 0x7f08001a
			public const int phone = 2131230746;
			
			// aapt resource value: 0x7f08001d
			public const int refresh = 2131230749;
			
			// aapt resource value: 0x7f08001b
			public const int submenu = 2131230747;
			
			// aapt resource value: 0x7f080013
			public const int textView1 = 2131230739;
			
			// aapt resource value: 0x7f080001
			public const int textView4 = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int textView5 = 2131230725;
			
			// aapt resource value: 0x7f080014
			public const int txtBarCodeSearch = 2131230740;
			
			// aapt resource value: 0x7f080002
			public const int txtItemCode = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int txtItemDescription = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int txtItemName = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int txtKeyWord = 2131230726;
			
			// aapt resource value: 0x7f080018
			public const int vendorMenu = 2131230744;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ItemMainLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LogInLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SplashLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int VendorMainLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int zxingscanneractivitylayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int zxingscannerfragmentlayout = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int vendorMenu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050009
			public const int CustomActionBarTheme = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int Layout_Color = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int Mono_Android_Theme_Splash = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int MyActionBar = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int MyActionBarTitleText = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int MyWindowBackGround = 2131034124;
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int button_confirm = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int button_gray = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int button_pad = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int label_caption = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int label_gray = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int textview_red = 2131034119;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
